name: Hello Workflow
on : 
 push: 

jobs:
 build:
  runs-on: ubuntu-latest 
  steps:
   - name : build
     run : echo hi,"${{vars.BUILD_NAME}}"

 test:
  runs-on : ubuntu-latest
  needs: build
  steps:
    - name : test
      run : echo This is "${{vars.TEST_NAME}}"

 deploy:
  runs-on : ubuntu-latest
  needs: test
  steps:
    - name : deployement
      run : echo This is "${{vars.DEPLOYMENT }}"

